[package]
name = "bounded-str-test"
version = "0.1.0"
edition = "2024"

[dependencies]
bounded-str = { path = "..", features = ["serde", "zeroize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
